/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as MainRouteImport } from './routes/_main'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as MainIndexRouteImport } from './routes/_main.index'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth.verify-email'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthSigninRouteImport } from './routes/auth.signin'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminBuyersRouteImport } from './routes/admin.buyers'
import { Route as AdminAuctionsRouteImport } from './routes/admin.auctions'
import { Route as AdminAssignmentsRouteImport } from './routes/admin.assignments'
import { Route as MainOnboardingRouteImport } from './routes/_main.onboarding'
import { Route as MainHelpRouteImport } from './routes/_main.help'
import { Route as MainCategoriesRouteImport } from './routes/_main.categories'
import { Route as MainAboutRouteImport } from './routes/_main.about'
import { Route as MainProtectedRouteImport } from './routes/_main._protected'
import { Route as DashboardListingsIndexRouteImport } from './routes/dashboard.listings.index'
import { Route as DashboardAuctionsIndexRouteImport } from './routes/dashboard.auctions.index'
import { Route as AdminSuppliersIndexRouteImport } from './routes/admin.suppliers.index'
import { Route as MainSuppliersIndexRouteImport } from './routes/_main.suppliers.index'
import { Route as MainServicesIndexRouteImport } from './routes/_main.services.index'
import { Route as MainProductsIndexRouteImport } from './routes/_main.products.index'
import { Route as MainAuctionsIndexRouteImport } from './routes/_main.auctions.index'
import { Route as DashboardListingsNewRouteImport } from './routes/dashboard.listings.new'
import { Route as DashboardAuctionsNewRouteImport } from './routes/dashboard.auctions.new'
import { Route as AdminSuppliersNewRouteImport } from './routes/admin.suppliers.new'
import { Route as MainSuppliersSupplierIdRouteImport } from './routes/_main.suppliers.$supplierId'
import { Route as MainServicesServiceIdRouteImport } from './routes/_main.services.$serviceId'
import { Route as MainProductsProductIdRouteImport } from './routes/_main.products.$productId'
import { Route as MainAuctionsAuctionIdRouteImport } from './routes/_main.auctions.$auctionId'
import { Route as MainProtectedWishlistRouteImport } from './routes/_main._protected.wishlist'
import { Route as MainProtectedProfileRouteImport } from './routes/_main._protected.profile'
import { Route as MainProtectedMessagesRouteImport } from './routes/_main._protected.messages'
import { Route as AdminSuppliersSupplierIdIndexRouteImport } from './routes/admin.suppliers.$supplierId.index'
import { Route as DashboardListingsListingIdEditRouteImport } from './routes/dashboard.listings.$listingId.edit'
import { Route as AdminSuppliersSupplierIdEditRouteImport } from './routes/admin.suppliers.$supplierId.edit'
import { Route as AdminSuppliersSupplierIdProductProductIdIndexRouteImport } from './routes/admin.suppliers.$supplierId.product.$productId.index'
import { Route as AdminSuppliersSupplierIdProductProductIdEditRouteImport } from './routes/admin.suppliers.$supplierId.product.$productId.edit'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBuyersRoute = AdminBuyersRouteImport.update({
  id: '/buyers',
  path: '/buyers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuctionsRoute = AdminAuctionsRouteImport.update({
  id: '/auctions',
  path: '/auctions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssignmentsRoute = AdminAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => AdminRoute,
} as any)
const MainOnboardingRoute = MainOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => MainRoute,
} as any)
const MainHelpRoute = MainHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => MainRoute,
} as any)
const MainCategoriesRoute = MainCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => MainRoute,
} as any)
const MainAboutRoute = MainAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MainRoute,
} as any)
const MainProtectedRoute = MainProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => MainRoute,
} as any)
const DashboardListingsIndexRoute = DashboardListingsIndexRouteImport.update({
  id: '/listings/',
  path: '/listings/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAuctionsIndexRoute = DashboardAuctionsIndexRouteImport.update({
  id: '/auctions/',
  path: '/auctions/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminSuppliersIndexRoute = AdminSuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => AdminRoute,
} as any)
const MainSuppliersIndexRoute = MainSuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => MainRoute,
} as any)
const MainServicesIndexRoute = MainServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => MainRoute,
} as any)
const MainProductsIndexRoute = MainProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => MainRoute,
} as any)
const MainAuctionsIndexRoute = MainAuctionsIndexRouteImport.update({
  id: '/auctions/',
  path: '/auctions/',
  getParentRoute: () => MainRoute,
} as any)
const DashboardListingsNewRoute = DashboardListingsNewRouteImport.update({
  id: '/listings/new',
  path: '/listings/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAuctionsNewRoute = DashboardAuctionsNewRouteImport.update({
  id: '/auctions/new',
  path: '/auctions/new',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminSuppliersNewRoute = AdminSuppliersNewRouteImport.update({
  id: '/suppliers/new',
  path: '/suppliers/new',
  getParentRoute: () => AdminRoute,
} as any)
const MainSuppliersSupplierIdRoute = MainSuppliersSupplierIdRouteImport.update({
  id: '/suppliers/$supplierId',
  path: '/suppliers/$supplierId',
  getParentRoute: () => MainRoute,
} as any)
const MainServicesServiceIdRoute = MainServicesServiceIdRouteImport.update({
  id: '/services/$serviceId',
  path: '/services/$serviceId',
  getParentRoute: () => MainRoute,
} as any)
const MainProductsProductIdRoute = MainProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => MainRoute,
} as any)
const MainAuctionsAuctionIdRoute = MainAuctionsAuctionIdRouteImport.update({
  id: '/auctions/$auctionId',
  path: '/auctions/$auctionId',
  getParentRoute: () => MainRoute,
} as any)
const MainProtectedWishlistRoute = MainProtectedWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => MainProtectedRoute,
} as any)
const MainProtectedProfileRoute = MainProtectedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MainProtectedRoute,
} as any)
const MainProtectedMessagesRoute = MainProtectedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => MainProtectedRoute,
} as any)
const AdminSuppliersSupplierIdIndexRoute =
  AdminSuppliersSupplierIdIndexRouteImport.update({
    id: '/suppliers/$supplierId/',
    path: '/suppliers/$supplierId/',
    getParentRoute: () => AdminRoute,
  } as any)
const DashboardListingsListingIdEditRoute =
  DashboardListingsListingIdEditRouteImport.update({
    id: '/listings/$listingId/edit',
    path: '/listings/$listingId/edit',
    getParentRoute: () => DashboardRoute,
  } as any)
const AdminSuppliersSupplierIdEditRoute =
  AdminSuppliersSupplierIdEditRouteImport.update({
    id: '/suppliers/$supplierId/edit',
    path: '/suppliers/$supplierId/edit',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminSuppliersSupplierIdProductProductIdIndexRoute =
  AdminSuppliersSupplierIdProductProductIdIndexRouteImport.update({
    id: '/suppliers/$supplierId/product/$productId/',
    path: '/suppliers/$supplierId/product/$productId/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminSuppliersSupplierIdProductProductIdEditRoute =
  AdminSuppliersSupplierIdProductProductIdEditRouteImport.update({
    id: '/suppliers/$supplierId/product/$productId/edit',
    path: '/suppliers/$supplierId/product/$productId/edit',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/about': typeof MainAboutRoute
  '/categories': typeof MainCategoriesRoute
  '/help': typeof MainHelpRoute
  '/onboarding': typeof MainOnboardingRoute
  '/admin/assignments': typeof AdminAssignmentsRoute
  '/admin/auctions': typeof AdminAuctionsRoute
  '/admin/buyers': typeof AdminBuyersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/services': typeof AdminServicesRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/messages': typeof MainProtectedMessagesRoute
  '/profile': typeof MainProtectedProfileRoute
  '/wishlist': typeof MainProtectedWishlistRoute
  '/auctions/$auctionId': typeof MainAuctionsAuctionIdRoute
  '/products/$productId': typeof MainProductsProductIdRoute
  '/services/$serviceId': typeof MainServicesServiceIdRoute
  '/suppliers/$supplierId': typeof MainSuppliersSupplierIdRoute
  '/admin/suppliers/new': typeof AdminSuppliersNewRoute
  '/dashboard/auctions/new': typeof DashboardAuctionsNewRoute
  '/dashboard/listings/new': typeof DashboardListingsNewRoute
  '/auctions/': typeof MainAuctionsIndexRoute
  '/products/': typeof MainProductsIndexRoute
  '/services/': typeof MainServicesIndexRoute
  '/suppliers/': typeof MainSuppliersIndexRoute
  '/admin/suppliers/': typeof AdminSuppliersIndexRoute
  '/dashboard/auctions/': typeof DashboardAuctionsIndexRoute
  '/dashboard/listings/': typeof DashboardListingsIndexRoute
  '/admin/suppliers/$supplierId/edit': typeof AdminSuppliersSupplierIdEditRoute
  '/dashboard/listings/$listingId/edit': typeof DashboardListingsListingIdEditRoute
  '/admin/suppliers/$supplierId/': typeof AdminSuppliersSupplierIdIndexRoute
  '/admin/suppliers/$supplierId/product/$productId/edit': typeof AdminSuppliersSupplierIdProductProductIdEditRoute
  '/admin/suppliers/$supplierId/product/$productId/': typeof AdminSuppliersSupplierIdProductProductIdIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/': typeof MainIndexRoute
  '/about': typeof MainAboutRoute
  '/categories': typeof MainCategoriesRoute
  '/help': typeof MainHelpRoute
  '/onboarding': typeof MainOnboardingRoute
  '/admin/assignments': typeof AdminAssignmentsRoute
  '/admin/auctions': typeof AdminAuctionsRoute
  '/admin/buyers': typeof AdminBuyersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/services': typeof AdminServicesRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/messages': typeof MainProtectedMessagesRoute
  '/profile': typeof MainProtectedProfileRoute
  '/wishlist': typeof MainProtectedWishlistRoute
  '/auctions/$auctionId': typeof MainAuctionsAuctionIdRoute
  '/products/$productId': typeof MainProductsProductIdRoute
  '/services/$serviceId': typeof MainServicesServiceIdRoute
  '/suppliers/$supplierId': typeof MainSuppliersSupplierIdRoute
  '/admin/suppliers/new': typeof AdminSuppliersNewRoute
  '/dashboard/auctions/new': typeof DashboardAuctionsNewRoute
  '/dashboard/listings/new': typeof DashboardListingsNewRoute
  '/auctions': typeof MainAuctionsIndexRoute
  '/products': typeof MainProductsIndexRoute
  '/services': typeof MainServicesIndexRoute
  '/suppliers': typeof MainSuppliersIndexRoute
  '/admin/suppliers': typeof AdminSuppliersIndexRoute
  '/dashboard/auctions': typeof DashboardAuctionsIndexRoute
  '/dashboard/listings': typeof DashboardListingsIndexRoute
  '/admin/suppliers/$supplierId/edit': typeof AdminSuppliersSupplierIdEditRoute
  '/dashboard/listings/$listingId/edit': typeof DashboardListingsListingIdEditRoute
  '/admin/suppliers/$supplierId': typeof AdminSuppliersSupplierIdIndexRoute
  '/admin/suppliers/$supplierId/product/$productId/edit': typeof AdminSuppliersSupplierIdProductProductIdEditRoute
  '/admin/suppliers/$supplierId/product/$productId': typeof AdminSuppliersSupplierIdProductProductIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/_main/_protected': typeof MainProtectedRouteWithChildren
  '/_main/about': typeof MainAboutRoute
  '/_main/categories': typeof MainCategoriesRoute
  '/_main/help': typeof MainHelpRoute
  '/_main/onboarding': typeof MainOnboardingRoute
  '/admin/assignments': typeof AdminAssignmentsRoute
  '/admin/auctions': typeof AdminAuctionsRoute
  '/admin/buyers': typeof AdminBuyersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/services': typeof AdminServicesRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/_main/': typeof MainIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/_main/_protected/messages': typeof MainProtectedMessagesRoute
  '/_main/_protected/profile': typeof MainProtectedProfileRoute
  '/_main/_protected/wishlist': typeof MainProtectedWishlistRoute
  '/_main/auctions/$auctionId': typeof MainAuctionsAuctionIdRoute
  '/_main/products/$productId': typeof MainProductsProductIdRoute
  '/_main/services/$serviceId': typeof MainServicesServiceIdRoute
  '/_main/suppliers/$supplierId': typeof MainSuppliersSupplierIdRoute
  '/admin/suppliers/new': typeof AdminSuppliersNewRoute
  '/dashboard/auctions/new': typeof DashboardAuctionsNewRoute
  '/dashboard/listings/new': typeof DashboardListingsNewRoute
  '/_main/auctions/': typeof MainAuctionsIndexRoute
  '/_main/products/': typeof MainProductsIndexRoute
  '/_main/services/': typeof MainServicesIndexRoute
  '/_main/suppliers/': typeof MainSuppliersIndexRoute
  '/admin/suppliers/': typeof AdminSuppliersIndexRoute
  '/dashboard/auctions/': typeof DashboardAuctionsIndexRoute
  '/dashboard/listings/': typeof DashboardListingsIndexRoute
  '/admin/suppliers/$supplierId/edit': typeof AdminSuppliersSupplierIdEditRoute
  '/dashboard/listings/$listingId/edit': typeof DashboardListingsListingIdEditRoute
  '/admin/suppliers/$supplierId/': typeof AdminSuppliersSupplierIdIndexRoute
  '/admin/suppliers/$supplierId/product/$productId/edit': typeof AdminSuppliersSupplierIdProductProductIdEditRoute
  '/admin/suppliers/$supplierId/product/$productId/': typeof AdminSuppliersSupplierIdProductProductIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/about'
    | '/categories'
    | '/help'
    | '/onboarding'
    | '/admin/assignments'
    | '/admin/auctions'
    | '/admin/buyers'
    | '/admin/categories'
    | '/admin/products'
    | '/admin/profile'
    | '/admin/services'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/admin/'
    | '/dashboard/'
    | '/messages'
    | '/profile'
    | '/wishlist'
    | '/auctions/$auctionId'
    | '/products/$productId'
    | '/services/$serviceId'
    | '/suppliers/$supplierId'
    | '/admin/suppliers/new'
    | '/dashboard/auctions/new'
    | '/dashboard/listings/new'
    | '/auctions/'
    | '/products/'
    | '/services/'
    | '/suppliers/'
    | '/admin/suppliers/'
    | '/dashboard/auctions/'
    | '/dashboard/listings/'
    | '/admin/suppliers/$supplierId/edit'
    | '/dashboard/listings/$listingId/edit'
    | '/admin/suppliers/$supplierId/'
    | '/admin/suppliers/$supplierId/product/$productId/edit'
    | '/admin/suppliers/$supplierId/product/$productId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/'
    | '/about'
    | '/categories'
    | '/help'
    | '/onboarding'
    | '/admin/assignments'
    | '/admin/auctions'
    | '/admin/buyers'
    | '/admin/categories'
    | '/admin/products'
    | '/admin/profile'
    | '/admin/services'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/admin'
    | '/dashboard'
    | '/messages'
    | '/profile'
    | '/wishlist'
    | '/auctions/$auctionId'
    | '/products/$productId'
    | '/services/$serviceId'
    | '/suppliers/$supplierId'
    | '/admin/suppliers/new'
    | '/dashboard/auctions/new'
    | '/dashboard/listings/new'
    | '/auctions'
    | '/products'
    | '/services'
    | '/suppliers'
    | '/admin/suppliers'
    | '/dashboard/auctions'
    | '/dashboard/listings'
    | '/admin/suppliers/$supplierId/edit'
    | '/dashboard/listings/$listingId/edit'
    | '/admin/suppliers/$supplierId'
    | '/admin/suppliers/$supplierId/product/$productId/edit'
    | '/admin/suppliers/$supplierId/product/$productId'
  id:
    | '__root__'
    | '/_main'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/_main/_protected'
    | '/_main/about'
    | '/_main/categories'
    | '/_main/help'
    | '/_main/onboarding'
    | '/admin/assignments'
    | '/admin/auctions'
    | '/admin/buyers'
    | '/admin/categories'
    | '/admin/products'
    | '/admin/profile'
    | '/admin/services'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/_main/'
    | '/admin/'
    | '/dashboard/'
    | '/_main/_protected/messages'
    | '/_main/_protected/profile'
    | '/_main/_protected/wishlist'
    | '/_main/auctions/$auctionId'
    | '/_main/products/$productId'
    | '/_main/services/$serviceId'
    | '/_main/suppliers/$supplierId'
    | '/admin/suppliers/new'
    | '/dashboard/auctions/new'
    | '/dashboard/listings/new'
    | '/_main/auctions/'
    | '/_main/products/'
    | '/_main/services/'
    | '/_main/suppliers/'
    | '/admin/suppliers/'
    | '/dashboard/auctions/'
    | '/dashboard/listings/'
    | '/admin/suppliers/$supplierId/edit'
    | '/dashboard/listings/$listingId/edit'
    | '/admin/suppliers/$supplierId/'
    | '/admin/suppliers/$supplierId/product/$productId/edit'
    | '/admin/suppliers/$supplierId/product/$productId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/buyers': {
      id: '/admin/buyers'
      path: '/buyers'
      fullPath: '/admin/buyers'
      preLoaderRoute: typeof AdminBuyersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/auctions': {
      id: '/admin/auctions'
      path: '/auctions'
      fullPath: '/admin/auctions'
      preLoaderRoute: typeof AdminAuctionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assignments': {
      id: '/admin/assignments'
      path: '/assignments'
      fullPath: '/admin/assignments'
      preLoaderRoute: typeof AdminAssignmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_main/onboarding': {
      id: '/_main/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof MainOnboardingRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/help': {
      id: '/_main/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof MainHelpRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/categories': {
      id: '/_main/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof MainCategoriesRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/about': {
      id: '/_main/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MainAboutRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/_protected': {
      id: '/_main/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainProtectedRouteImport
      parentRoute: typeof MainRoute
    }
    '/dashboard/listings/': {
      id: '/dashboard/listings/'
      path: '/listings'
      fullPath: '/dashboard/listings/'
      preLoaderRoute: typeof DashboardListingsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/auctions/': {
      id: '/dashboard/auctions/'
      path: '/auctions'
      fullPath: '/dashboard/auctions/'
      preLoaderRoute: typeof DashboardAuctionsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/suppliers/': {
      id: '/admin/suppliers/'
      path: '/suppliers'
      fullPath: '/admin/suppliers/'
      preLoaderRoute: typeof AdminSuppliersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_main/suppliers/': {
      id: '/_main/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof MainSuppliersIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/services/': {
      id: '/_main/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof MainServicesIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/products/': {
      id: '/_main/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof MainProductsIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/auctions/': {
      id: '/_main/auctions/'
      path: '/auctions'
      fullPath: '/auctions/'
      preLoaderRoute: typeof MainAuctionsIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/dashboard/listings/new': {
      id: '/dashboard/listings/new'
      path: '/listings/new'
      fullPath: '/dashboard/listings/new'
      preLoaderRoute: typeof DashboardListingsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/auctions/new': {
      id: '/dashboard/auctions/new'
      path: '/auctions/new'
      fullPath: '/dashboard/auctions/new'
      preLoaderRoute: typeof DashboardAuctionsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/suppliers/new': {
      id: '/admin/suppliers/new'
      path: '/suppliers/new'
      fullPath: '/admin/suppliers/new'
      preLoaderRoute: typeof AdminSuppliersNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_main/suppliers/$supplierId': {
      id: '/_main/suppliers/$supplierId'
      path: '/suppliers/$supplierId'
      fullPath: '/suppliers/$supplierId'
      preLoaderRoute: typeof MainSuppliersSupplierIdRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/services/$serviceId': {
      id: '/_main/services/$serviceId'
      path: '/services/$serviceId'
      fullPath: '/services/$serviceId'
      preLoaderRoute: typeof MainServicesServiceIdRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/products/$productId': {
      id: '/_main/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof MainProductsProductIdRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/auctions/$auctionId': {
      id: '/_main/auctions/$auctionId'
      path: '/auctions/$auctionId'
      fullPath: '/auctions/$auctionId'
      preLoaderRoute: typeof MainAuctionsAuctionIdRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/_protected/wishlist': {
      id: '/_main/_protected/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof MainProtectedWishlistRouteImport
      parentRoute: typeof MainProtectedRoute
    }
    '/_main/_protected/profile': {
      id: '/_main/_protected/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof MainProtectedProfileRouteImport
      parentRoute: typeof MainProtectedRoute
    }
    '/_main/_protected/messages': {
      id: '/_main/_protected/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MainProtectedMessagesRouteImport
      parentRoute: typeof MainProtectedRoute
    }
    '/admin/suppliers/$supplierId/': {
      id: '/admin/suppliers/$supplierId/'
      path: '/suppliers/$supplierId'
      fullPath: '/admin/suppliers/$supplierId/'
      preLoaderRoute: typeof AdminSuppliersSupplierIdIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/listings/$listingId/edit': {
      id: '/dashboard/listings/$listingId/edit'
      path: '/listings/$listingId/edit'
      fullPath: '/dashboard/listings/$listingId/edit'
      preLoaderRoute: typeof DashboardListingsListingIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/suppliers/$supplierId/edit': {
      id: '/admin/suppliers/$supplierId/edit'
      path: '/suppliers/$supplierId/edit'
      fullPath: '/admin/suppliers/$supplierId/edit'
      preLoaderRoute: typeof AdminSuppliersSupplierIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/suppliers/$supplierId/product/$productId/': {
      id: '/admin/suppliers/$supplierId/product/$productId/'
      path: '/suppliers/$supplierId/product/$productId'
      fullPath: '/admin/suppliers/$supplierId/product/$productId/'
      preLoaderRoute: typeof AdminSuppliersSupplierIdProductProductIdIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/suppliers/$supplierId/product/$productId/edit': {
      id: '/admin/suppliers/$supplierId/product/$productId/edit'
      path: '/suppliers/$supplierId/product/$productId/edit'
      fullPath: '/admin/suppliers/$supplierId/product/$productId/edit'
      preLoaderRoute: typeof AdminSuppliersSupplierIdProductProductIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface MainProtectedRouteChildren {
  MainProtectedMessagesRoute: typeof MainProtectedMessagesRoute
  MainProtectedProfileRoute: typeof MainProtectedProfileRoute
  MainProtectedWishlistRoute: typeof MainProtectedWishlistRoute
}

const MainProtectedRouteChildren: MainProtectedRouteChildren = {
  MainProtectedMessagesRoute: MainProtectedMessagesRoute,
  MainProtectedProfileRoute: MainProtectedProfileRoute,
  MainProtectedWishlistRoute: MainProtectedWishlistRoute,
}

const MainProtectedRouteWithChildren = MainProtectedRoute._addFileChildren(
  MainProtectedRouteChildren,
)

interface MainRouteChildren {
  MainProtectedRoute: typeof MainProtectedRouteWithChildren
  MainAboutRoute: typeof MainAboutRoute
  MainCategoriesRoute: typeof MainCategoriesRoute
  MainHelpRoute: typeof MainHelpRoute
  MainOnboardingRoute: typeof MainOnboardingRoute
  MainIndexRoute: typeof MainIndexRoute
  MainAuctionsAuctionIdRoute: typeof MainAuctionsAuctionIdRoute
  MainProductsProductIdRoute: typeof MainProductsProductIdRoute
  MainServicesServiceIdRoute: typeof MainServicesServiceIdRoute
  MainSuppliersSupplierIdRoute: typeof MainSuppliersSupplierIdRoute
  MainAuctionsIndexRoute: typeof MainAuctionsIndexRoute
  MainProductsIndexRoute: typeof MainProductsIndexRoute
  MainServicesIndexRoute: typeof MainServicesIndexRoute
  MainSuppliersIndexRoute: typeof MainSuppliersIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainProtectedRoute: MainProtectedRouteWithChildren,
  MainAboutRoute: MainAboutRoute,
  MainCategoriesRoute: MainCategoriesRoute,
  MainHelpRoute: MainHelpRoute,
  MainOnboardingRoute: MainOnboardingRoute,
  MainIndexRoute: MainIndexRoute,
  MainAuctionsAuctionIdRoute: MainAuctionsAuctionIdRoute,
  MainProductsProductIdRoute: MainProductsProductIdRoute,
  MainServicesServiceIdRoute: MainServicesServiceIdRoute,
  MainSuppliersSupplierIdRoute: MainSuppliersSupplierIdRoute,
  MainAuctionsIndexRoute: MainAuctionsIndexRoute,
  MainProductsIndexRoute: MainProductsIndexRoute,
  MainServicesIndexRoute: MainServicesIndexRoute,
  MainSuppliersIndexRoute: MainSuppliersIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

interface AdminRouteChildren {
  AdminAssignmentsRoute: typeof AdminAssignmentsRoute
  AdminAuctionsRoute: typeof AdminAuctionsRoute
  AdminBuyersRoute: typeof AdminBuyersRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminSuppliersNewRoute: typeof AdminSuppliersNewRoute
  AdminSuppliersIndexRoute: typeof AdminSuppliersIndexRoute
  AdminSuppliersSupplierIdEditRoute: typeof AdminSuppliersSupplierIdEditRoute
  AdminSuppliersSupplierIdIndexRoute: typeof AdminSuppliersSupplierIdIndexRoute
  AdminSuppliersSupplierIdProductProductIdEditRoute: typeof AdminSuppliersSupplierIdProductProductIdEditRoute
  AdminSuppliersSupplierIdProductProductIdIndexRoute: typeof AdminSuppliersSupplierIdProductProductIdIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAssignmentsRoute: AdminAssignmentsRoute,
  AdminAuctionsRoute: AdminAuctionsRoute,
  AdminBuyersRoute: AdminBuyersRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminSuppliersNewRoute: AdminSuppliersNewRoute,
  AdminSuppliersIndexRoute: AdminSuppliersIndexRoute,
  AdminSuppliersSupplierIdEditRoute: AdminSuppliersSupplierIdEditRoute,
  AdminSuppliersSupplierIdIndexRoute: AdminSuppliersSupplierIdIndexRoute,
  AdminSuppliersSupplierIdProductProductIdEditRoute:
    AdminSuppliersSupplierIdProductProductIdEditRoute,
  AdminSuppliersSupplierIdProductProductIdIndexRoute:
    AdminSuppliersSupplierIdProductProductIdIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAuctionsNewRoute: typeof DashboardAuctionsNewRoute
  DashboardListingsNewRoute: typeof DashboardListingsNewRoute
  DashboardAuctionsIndexRoute: typeof DashboardAuctionsIndexRoute
  DashboardListingsIndexRoute: typeof DashboardListingsIndexRoute
  DashboardListingsListingIdEditRoute: typeof DashboardListingsListingIdEditRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAuctionsNewRoute: DashboardAuctionsNewRoute,
  DashboardListingsNewRoute: DashboardListingsNewRoute,
  DashboardAuctionsIndexRoute: DashboardAuctionsIndexRoute,
  DashboardListingsIndexRoute: DashboardListingsIndexRoute,
  DashboardListingsListingIdEditRoute: DashboardListingsListingIdEditRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
